// ============================================================================
// Renders the commands page entirely from data/commands.json. That file is
// generated by scripts/generate_commands.py by scanning the cogs - so
// adding a new @commands.command in a cog and re-running the script (or
// letting the GitHub Action do it on push) is the only step needed to get
// it showing up here. Nothing on this page is hand-maintained.
// ============================================================================

const ICONS = {
  shield: `<path d="M12 2l8 4v6c0 5-3.5 8.5-8 10-4.5-1.5-8-5-8-10V6l8-4z"/>`,
  sparkles: `<path d="M12 3l1.8 5.2L19 10l-5.2 1.8L12 17l-1.8-5.2L5 10l5.2-1.8L12 3z"/><path d="M19 15l.8 2.2L22 18l-2.2.8L19 21l-.8-2.2L16 18l2.2-.8L19 15z"/>`,
  webhook: `<circle cx="6" cy="12" r="3"/><path d="M9 12h6l3-6"/><circle cx="18" cy="6" r="2"/><path d="M9 12l4 7"/><circle cx="15" cy="19" r="2"/>`,
  gift: `<rect x="3" y="8" width="18" height="13" rx="1"/><path d="M3 12h18M12 8v13"/><path d="M12 8c-2 0-3-1.2-3-2.5S10 3 12 3s3 1.2 3 2.5S14 8 12 8z"/>`,
  server: `<rect x="3" y="4" width="18" height="7" rx="1.5"/><rect x="3" y="13" width="18" height="7" rx="1.5"/><circle cx="7" cy="7.5" r="1"/><circle cx="7" cy="16.5" r="1"/>`,
  wrench: `<path d="M14.7 6.3a4 4 0 1 0-5.4 5.4L3 18l3 3 6.3-6.3a4 4 0 0 0 5.4-5.4l-2.8 2.8-2-2 2.8-2.8z"/>`,
  smile: `<circle cx="12" cy="12" r="9"/><path d="M8 14s1.5 2 4 2 4-2 4-2M9 9h.01M15 9h.01"/>`,
  crown: `<path d="M3 8l4 3 5-6 5 6 4-3-2 11H5L3 8z"/>`,
};
const DEFAULT_ICON = ICONS.sparkles;

const state = {
  categories: [],
  activeCategory: "all",
  query: "",
};

const el = (id) => document.getElementById(id);
const grid = el("commands-body");
const pillsEl = el("category-pills");
const searchInput = el("search-input");
const metaEl = el("commands-meta");

function escapeHtml(str) {
  const div = document.createElement("div");
  div.textContent = str;
  return div.innerHTML;
}

function iconSvg(name) {
  const path = ICONS[name] || DEFAULT_ICON;
  return `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${path}</svg>`;
}

function matchesQuery(cmd, q) {
  if (!q) return true;
  const haystack = [cmd.name, cmd.description, ...(cmd.aliases || [])]
    .join(" ")
    .toLowerCase();
  return haystack.includes(q.toLowerCase());
}

function renderPills() {
  const total = state.categories.reduce((n, c) => n + c.commands.length, 0);
  const pills = [{ name: "all", label: "All", count: total }].concat(
    state.categories.map((c) => ({
      name: c.name,
      label: c.name,
      count: c.commands.length,
    })),
  );

  pillsEl.innerHTML = pills
    .map(
      (p) => `
      <button class="category-pill${state.activeCategory === p.name ? " active" : ""}" data-cat="${escapeHtml(p.name)}">
        ${escapeHtml(p.label)} <span class="count">${p.count}</span>
      </button>
    `,
    )
    .join("");

  pillsEl.querySelectorAll(".category-pill").forEach((btn) => {
    btn.addEventListener("click", () => {
      state.activeCategory = btn.dataset.cat;
      render();
    });
  });
}

function renderCommandCard(cmd) {
  const aliasTags = (cmd.aliases || [])
    .map((a) => `<span class="alias-tag">!${escapeHtml(a)}</span>`)
    .join("");
  const permTags = (cmd.permissions || [])
    .map(
      (p) => `
      <span class="perm-tag">
        <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2l8 4v6c0 5-3.5 8.5-8 10-4.5-1.5-8-5-8-10V6l8-4z"/></svg>
        ${escapeHtml(p)}
      </span>
    `,
    )
    .join("");

  return `
    <div class="command-card">
      <div class="command-card-top">
        <span class="command-name">!${escapeHtml(cmd.name)}</span>
        ${cmd.is_group ? '<span class="group-pill">Group</span>' : ""}
      </div>
      <p class="command-desc">${escapeHtml(cmd.description || "No description provided.")}</p>
      <div class="command-tags">${aliasTags}${permTags}</div>
    </div>
  `;
}

function render() {
  const q = state.query.trim();
  let visibleCommandCount = 0;
  let sectionsHtml = "";

  for (const cat of state.categories) {
    if (state.activeCategory !== "all" && state.activeCategory !== cat.name)
      continue;

    const matches = cat.commands.filter((c) => matchesQuery(c, q));
    if (matches.length === 0) continue;

    visibleCommandCount += matches.length;
    sectionsHtml += `
      <section class="category-section">
        <div class="category-heading">
          <div class="category-icon">${iconSvg(cat.icon)}</div>
          <h2>${escapeHtml(cat.name)}</h2>
          <span class="count-pill">${matches.length}</span>
        </div>
        <div class="command-grid">
          ${matches.map(renderCommandCard).join("")}
        </div>
      </section>
    `;
  }

  grid.innerHTML =
    visibleCommandCount > 0
      ? sectionsHtml
      : `<div class="no-results">No commands match "${escapeHtml(q)}".</div>`;
}

async function init() {
  try {
    const res = await fetch("../data/commands.json", { cache: "no-store" });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    state.categories = data.categories || [];
  } catch (err) {
    grid.innerHTML = `<div class="no-results">Couldn't load the command list right now.</div>`;
    metaEl.textContent = "";
    return;
  }

  const totalCommands = state.categories.reduce(
    (n, c) => n + c.commands.length,
    0,
  );
  metaEl.textContent = `${totalCommands} commands across ${state.categories.length} categories.`;

  renderPills();
  render();
}

searchInput.addEventListener("input", (e) => {
  state.query = e.target.value;
  render();
});

init();
